apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: all-viewer-binding
  namespace: development
subjects:
  - kind: User
    name: developer1
    namespace: development
  - kind: User
    name: security-specialist1
    namespace: development
roleRef:
  kind: Role
  name: all-viewer
  apiGroup: rbac.authorization.k8s.io
