apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-viewer-binding
  namespace: development
subjects:
  - kind: User
    name: product-owner1
    namespace: development
roleRef:
  kind: Role
  name: secret-viewer
  apiGroup: rbac.authorization.k8s.io
